name: Update GitHub Streak

on:
  schedule:
    - cron: "15 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  streak:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Streak
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&background=0D1117&ring=38bdf8&fire=0ea5e9&currStreakLabel=38bdf8&sideLabels=cbd5e1&dates=64748d&border_radius=8
          path: profile/streak-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Streak
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak-dark.svg

          git diff --cached --quiet || git commit -m "Update GitHub streak"

          git push
